#!/bin/sh
NAME=leptoninit
ALLOCSCRIPT=/usr/bin/allocate_gpio_pico.sh
DESC="Initialization for Lepton sensor"

test -f $ALLOCSCRIPT || exit 0

set -e

case "$1" in
    start)
        echo "Initializing Lepton GPIO"
        $ALLOCSCRIPT
        echo "Inserting v4l2loopback module"
        modprobe v4l2loopback
        ;;
    stop)
        echo -n "Removing v4l2loopback"
        rmmod v4l2loopback
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0

